const SET_TOKEN = "SET_TOKEN";
const SET_TOKEN_FAILED = "SET_TOKEN_FAILED";

const DISC_INFO_REQUESTED = "DISC_INFO_REQUESTED";
const DISC_INFO_PENDING = "DISC_INFO_PENDING";
const DISC_INFO_RECIEVED = "DISC_INFO_RECIEVED";
const DISC_INFO_FAILED = "DISC_INFO_FAILED";

export {
  SET_TOKEN,
  SET_TOKEN_FAILED,
  DISC_INFO_REQUESTED,
  DISC_INFO_PENDING,
  DISC_INFO_RECIEVED,
  DISC_INFO_FAILED
};
